// <auto-generated />
using System;
using AlIkhwanBeasiswa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlIkhwanBeasiswa.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006073907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AlumniKontribusi", b =>
                {
                    b.Property<int>("KontribusiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kontribusi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KontribusiId"));

                    b.Property<string>("DeskripsiKontribusi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi_kontribusi");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<decimal?>("NominalDonasi")
                        .HasColumnType("numeric")
                        .HasColumnName("nominal_donasi");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("status_aktif");

                    b.Property<DateTime>("TanggalKontribusi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_kontribusi");

                    b.Property<string>("TipeKontribusi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipe_kontribusi");

                    b.HasKey("KontribusiId");

                    b.HasIndex("MahasiswaId");

                    b.ToTable("alumni_kontribusi");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AlumniTracerKarir", b =>
                {
                    b.Property<int>("TracerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tracer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TracerId"));

                    b.Property<string>("BidangPekerjaan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bidang_pekerjaan");

                    b.Property<int>("BulanBergabung")
                        .HasColumnType("integer")
                        .HasColumnName("bulan_bergabung");

                    b.Property<int?>("BulanSelesai")
                        .HasColumnType("integer")
                        .HasColumnName("bulan_selesai");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jabatan");

                    b.Property<string>("KeselarasanJurusan")
                        .HasColumnType("text")
                        .HasColumnName("keselarasan_jurusan");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<bool>("MasihBekerja")
                        .HasColumnType("boolean")
                        .HasColumnName("masih_bekerja");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_perusahaan");

                    b.Property<string>("RentangGaji")
                        .HasColumnType("text")
                        .HasColumnName("rentang_gaji");

                    b.Property<int>("StatusPekerjaan")
                        .HasColumnType("integer")
                        .HasColumnName("status_pekerjaan");

                    b.Property<int>("TahunBergabung")
                        .HasColumnType("integer")
                        .HasColumnName("tahun_bergabung");

                    b.Property<int?>("TahunSelesai")
                        .HasColumnType("integer")
                        .HasColumnName("tahun_selesai");

                    b.HasKey("TracerId");

                    b.HasIndex("MahasiswaId");

                    b.ToTable("alumni_tracer_karir");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppPengurus", b =>
                {
                    b.Property<int>("PengurusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pengurus_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PengurusId"));

                    b.Property<string>("AlamatLengkap")
                        .HasColumnType("text")
                        .HasColumnName("alamat_lengkap");

                    b.Property<string>("Divisi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisi");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FotoProfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_profil_url");

                    b.Property<string>("Gelar")
                        .HasColumnType("text")
                        .HasColumnName("gelar");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jabatan");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_lengkap");

                    b.Property<string>("Nip")
                        .HasColumnType("text")
                        .HasColumnName("nip");

                    b.Property<string>("NoTelp")
                        .HasColumnType("text")
                        .HasColumnName("no_telp");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("status_aktif");

                    b.Property<string>("TandaTanganDigitalUrl")
                        .HasColumnType("text")
                        .HasColumnName("tanda_tangan_digital_url");

                    b.Property<DateTime?>("TanggalAkhirMenjabat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_akhir_menjabat");

                    b.Property<DateTime>("TanggalMulaiMenjabat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_mulai_menjabat");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PengurusId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("pengurus");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modul");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.HasKey("PermissionId");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppRolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUserProfile", b =>
                {
                    b.Property<int>("ProfileLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("profile_link_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileLinkId"));

                    b.Property<int?>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<int?>("SiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("siswa_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileLinkId");

                    b.HasIndex("MahasiswaId");

                    b.HasIndex("SiswaId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.ApprovalBeasiswa", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("approval_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalId"));

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("integer")
                        .HasColumnName("approver_user_id");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("text")
                        .HasColumnName("catatan_approval");

                    b.Property<int>("PengajuanId")
                        .HasColumnType("integer")
                        .HasColumnName("pengajuan_id");

                    b.Property<int>("StatusApproval")
                        .HasColumnType("integer")
                        .HasColumnName("status_approval");

                    b.Property<DateTime>("TanggalApproval")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_approval");

                    b.Property<int>("TingkatApproval")
                        .HasColumnType("integer")
                        .HasColumnName("tingkat_approval");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("PengajuanId", "TingkatApproval")
                        .IsUnique();

                    b.ToTable("approval_beasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", b =>
                {
                    b.Property<int>("MahasiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MahasiswaId"));

                    b.Property<string>("AlamatLengkap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alamat_lengkap");

                    b.Property<bool>("CalonKaderisasi")
                        .HasColumnType("boolean")
                        .HasColumnName("calon_kaderisasi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_mahasiswa");

                    b.Property<string>("NamaPanggilan")
                        .HasColumnType("text")
                        .HasColumnName("nama_panggilan");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_telp");

                    b.Property<int>("OrangTuaId")
                        .HasColumnType("integer")
                        .HasColumnName("orang_tua_id");

                    b.Property<int>("StatusAkademik")
                        .HasColumnType("integer")
                        .HasColumnName("status_akademik");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_lahir");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tempat_lahir");

                    b.HasKey("MahasiswaId");

                    b.HasIndex("OrangTuaId");

                    b.ToTable("mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanNilaiSekolah", b =>
                {
                    b.Property<int>("NilaiSekolahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nilai_sekolah_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NilaiSekolahId"));

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("NamaPelajaran")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_pelajaran");

                    b.Property<decimal>("NilaiRata")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_rata");

                    b.Property<decimal?>("NilaiUAS")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_uas");

                    b.Property<decimal?>("NilaiUTS")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_uts");

                    b.Property<int>("PendidikanId")
                        .HasColumnType("integer")
                        .HasColumnName("pendidikan_id");

                    b.Property<int>("Semester")
                        .HasColumnType("integer")
                        .HasColumnName("semester");

                    b.Property<int>("SiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("siswa_id");

                    b.HasKey("NilaiSekolahId");

                    b.HasIndex("PendidikanId");

                    b.HasIndex("SiswaId");

                    b.ToTable("nilai_sekolah");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanNilaiUniv", b =>
                {
                    b.Property<int>("NilaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nilai_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NilaiId"));

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<string>("MataKuliah")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mata_kuliah");

                    b.Property<decimal>("NilaiRata")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_rata");

                    b.Property<decimal?>("NilaiUAS")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_uas");

                    b.Property<decimal?>("NilaiUTS")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_uts");

                    b.Property<int>("Semester")
                        .HasColumnType("integer")
                        .HasColumnName("semester");

                    b.Property<int>("Sks")
                        .HasColumnType("integer")
                        .HasColumnName("sks");

                    b.Property<int>("UnivId")
                        .HasColumnType("integer")
                        .HasColumnName("univ_id");

                    b.Property<int?>("UniversitasUnivId")
                        .HasColumnType("integer")
                        .HasColumnName("universitas_univ_id");

                    b.HasKey("NilaiId");

                    b.HasIndex("MahasiswaId");

                    b.HasIndex("UniversitasUnivId");

                    b.ToTable("nilai_univ");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanOrangTua", b =>
                {
                    b.Property<int>("OrangTuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orang_tua_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrangTuaId"));

                    b.Property<string>("EmailAyah")
                        .HasColumnType("text")
                        .HasColumnName("email_ayah");

                    b.Property<string>("EmailIbu")
                        .HasColumnType("text")
                        .HasColumnName("email_ibu");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("NamaAyah")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_ayah");

                    b.Property<string>("NamaIbu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_ibu");

                    b.Property<string>("NoTelpAyah")
                        .HasColumnType("text")
                        .HasColumnName("no_telp_ayah");

                    b.Property<string>("NoTelpIbu")
                        .HasColumnType("text")
                        .HasColumnName("no_telp_ibu");

                    b.Property<string>("PekerjaanAyah")
                        .HasColumnType("text")
                        .HasColumnName("pekerjaan_ayah");

                    b.Property<string>("PekerjaanIbu")
                        .HasColumnType("text")
                        .HasColumnName("pekerjaan_ibu");

                    b.Property<bool>("TelahMeninggalAyah")
                        .HasColumnType("boolean")
                        .HasColumnName("telah_meninggal_ayah");

                    b.Property<bool>("TelahMeninggalIbu")
                        .HasColumnType("boolean")
                        .HasColumnName("telah_meninggal_ibu");

                    b.HasKey("OrangTuaId");

                    b.ToTable("orang_tua");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanPendidikan", b =>
                {
                    b.Property<int>("PendidikanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pendidikan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PendidikanId"));

                    b.Property<string>("AlamatSekolah")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alamat_sekolah");

                    b.Property<string>("EmailSekolah")
                        .HasColumnType("text")
                        .HasColumnName("email_sekolah");

                    b.Property<string>("Jenjang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jenjang");

                    b.Property<bool>("MasihDalamPendidikan")
                        .HasColumnType("boolean")
                        .HasColumnName("masih_dalam_pendidikan");

                    b.Property<string>("NamaSekolah")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_sekolah");

                    b.Property<string>("NoTelpSekolah")
                        .HasColumnType("text")
                        .HasColumnName("no_telp_sekolah");

                    b.Property<int>("SiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("siswa_id");

                    b.Property<DateTime?>("TanggalKeluar")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_keluar");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_masuk");

                    b.HasKey("PendidikanId");

                    b.HasIndex("SiswaId");

                    b.ToTable("pendidikan_sekolah");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("siswa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiswaId"));

                    b.Property<string>("AlamatLengkap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alamat_lengkap");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("NamaPanggilan")
                        .HasColumnType("text")
                        .HasColumnName("nama_panggilan");

                    b.Property<string>("NamaSiswa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_siswa");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_telp");

                    b.Property<int>("OrangTuaId")
                        .HasColumnType("integer")
                        .HasColumnName("orang_tua_id");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_lahir");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tempat_lahir");

                    b.HasKey("SiswaId");

                    b.HasIndex("OrangTuaId");

                    b.ToTable("siswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanUniversitas", b =>
                {
                    b.Property<int>("UnivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("univ_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnivId"));

                    b.Property<string>("AlamatUniversitas")
                        .HasColumnType("text")
                        .HasColumnName("alamat_universitas");

                    b.Property<string>("EmailUniversitas")
                        .HasColumnType("text")
                        .HasColumnName("email_universitas");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("Jenjang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jenjang");

                    b.Property<int>("JumlahSemester")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah_semester");

                    b.Property<int>("JumlahTahun")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah_tahun");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jurusan");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<bool>("MasihBerjalan")
                        .HasColumnType("boolean")
                        .HasColumnName("masih_berjalan");

                    b.Property<string>("NamaUniversitas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_universitas");

                    b.Property<string>("NoTelpUniversitas")
                        .HasColumnType("text")
                        .HasColumnName("no_telp_universitas");

                    b.Property<DateTime?>("TanggalLulus")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_lulus");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_masuk");

                    b.HasKey("UnivId");

                    b.HasIndex("MahasiswaId");

                    b.ToTable("universitas");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiKegiatan", b =>
                {
                    b.Property<int>("KegiatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kegiatan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KegiatanId"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<string>("NamaKegiatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_kegiatan");

                    b.Property<DateTime>("TanggalKegiatan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_kegiatan");

                    b.Property<string>("Tempat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tempat");

                    b.Property<string>("TipeKegiatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipe_kegiatan");

                    b.Property<bool>("WajibHadir")
                        .HasColumnType("boolean")
                        .HasColumnName("wajib_hadir");

                    b.HasKey("KegiatanId");

                    b.ToTable("kaderisasi_kegiatan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiPresensi", b =>
                {
                    b.Property<int>("PresensiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("presensi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PresensiId"));

                    b.Property<int>("KegiatanId")
                        .HasColumnType("integer")
                        .HasColumnName("kegiatan_id");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<int>("StatusKehadiran")
                        .HasColumnType("integer")
                        .HasColumnName("status_kehadiran");

                    b.Property<DateTime>("WaktuPresensi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_presensi");

                    b.HasKey("PresensiId");

                    b.HasIndex("MahasiswaId");

                    b.HasIndex("KegiatanId", "MahasiswaId")
                        .IsUnique();

                    b.ToTable("kaderisasi_presensi");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiProfil", b =>
                {
                    b.Property<int>("KaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kader_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KaderId"));

                    b.Property<string>("CatatanPerkembangan")
                        .HasColumnType("text")
                        .HasColumnName("catatan_perkembangan");

                    b.Property<string>("KelompokHalaqah")
                        .HasColumnType("text")
                        .HasColumnName("kelompok_halaqah");

                    b.Property<int>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<string>("NamaMurabbi")
                        .HasColumnType("text")
                        .HasColumnName("nama_murabbi");

                    b.Property<int>("StatusKader")
                        .HasColumnType("integer")
                        .HasColumnName("status_kader");

                    b.Property<DateTime>("TanggalBergabung")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_bergabung");

                    b.Property<string>("TingkatPembinaan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tingkat_pembinaan");

                    b.HasKey("KaderId");

                    b.HasIndex("MahasiswaId")
                        .IsUnique();

                    b.ToTable("kaderisasi_profil");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PencairanBeasiswa", b =>
                {
                    b.Property<int>("PencairanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pencairan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PencairanId"));

                    b.Property<decimal>("Biaya")
                        .HasColumnType("numeric")
                        .HasColumnName("biaya");

                    b.Property<string>("BuktiPembayaran")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bukti_pembayaran");

                    b.Property<int?>("DicairkanOlehUserId")
                        .HasColumnType("integer")
                        .HasColumnName("dicairkan_oleh_user_id");

                    b.Property<string>("InformasiTambahan")
                        .HasColumnType("text")
                        .HasColumnName("informasi_tambahan");

                    b.Property<string>("NomorReferensiBank")
                        .HasColumnType("text")
                        .HasColumnName("nomor_referensi_bank");

                    b.Property<int>("PengajuanId")
                        .HasColumnType("integer")
                        .HasColumnName("pengajuan_id");

                    b.Property<int>("StatusPencairan")
                        .HasColumnType("integer")
                        .HasColumnName("status_pencairan");

                    b.Property<DateTime>("TanggalPembayaran")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_pembayaran");

                    b.Property<int>("TerminKe")
                        .HasColumnType("integer")
                        .HasColumnName("termin_ke");

                    b.HasKey("PencairanId");

                    b.HasIndex("DicairkanOlehUserId");

                    b.HasIndex("PengajuanId");

                    b.ToTable("pencairan_beasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", b =>
                {
                    b.Property<int>("PengajuanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pengajuan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PengajuanId"));

                    b.Property<string>("CatatanPengajuan")
                        .HasColumnType("text")
                        .HasColumnName("catatan_pengajuan");

                    b.Property<int?>("MahasiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("mahasiswa_id");

                    b.Property<decimal>("NilaiRataRata")
                        .HasColumnType("numeric")
                        .HasColumnName("nilai_rata_rata");

                    b.Property<decimal>("PaguBeasiswa")
                        .HasColumnType("numeric")
                        .HasColumnName("pagu_beasiswa");

                    b.Property<decimal>("PaguTertanggung")
                        .HasColumnType("numeric")
                        .HasColumnName("pagu_tertanggung");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("integer")
                        .HasColumnName("periode_id");

                    b.Property<int?>("SiswaId")
                        .HasColumnType("integer")
                        .HasColumnName("siswa_id");

                    b.Property<int>("StatusPengajuan")
                        .HasColumnType("integer")
                        .HasColumnName("status_pengajuan");

                    b.Property<DateTime>("TanggalPengajuan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_pengajuan");

                    b.Property<bool>("TelahDibayarLunas")
                        .HasColumnType("boolean")
                        .HasColumnName("telah_dibayar_lunas");

                    b.Property<int>("TipePenerima")
                        .HasColumnType("integer")
                        .HasColumnName("tipe_penerima");

                    b.HasKey("PengajuanId");

                    b.HasIndex("MahasiswaId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("SiswaId");

                    b.ToTable("pengajuan_beasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PeriodeBeasiswa", b =>
                {
                    b.Property<int>("PeriodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("periode_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodeId"));

                    b.Property<int>("KuotaMahasiswa")
                        .HasColumnType("integer")
                        .HasColumnName("kuota_mahasiswa");

                    b.Property<int>("KuotaSiswa")
                        .HasColumnType("integer")
                        .HasColumnName("kuota_siswa");

                    b.Property<string>("NamaPeriode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_periode");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("status_aktif");

                    b.Property<DateTime>("TanggalMulaiDaftar")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_mulai_daftar");

                    b.Property<DateTime>("TanggalSelesaiDaftar")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_selesai_daftar");

                    b.Property<decimal>("TotalAnggaranPagu")
                        .HasColumnType("numeric")
                        .HasColumnName("total_anggaran_pagu");

                    b.HasKey("PeriodeId");

                    b.ToTable("periode_beasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalBanner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("banner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BannerId"));

                    b.Property<string>("GambarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gambar_url");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("judul");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("status_aktif");

                    b.Property<string>("Subjudul")
                        .HasColumnType("text")
                        .HasColumnName("subjudul");

                    b.Property<int>("Urutan")
                        .HasColumnType("integer")
                        .HasColumnName("urutan");

                    b.HasKey("BannerId");

                    b.ToTable("portal_banner");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalDokumenPenerima", b =>
                {
                    b.Property<int>("DokumenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dokumen_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DokumenId"));

                    b.Property<string>("CatatanRevisi")
                        .HasColumnType("text")
                        .HasColumnName("catatan_revisi");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("NamaFileAsli")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_file_asli");

                    b.Property<int>("PengajuanId")
                        .HasColumnType("integer")
                        .HasColumnName("pengajuan_id");

                    b.Property<string>("StatusVerifikasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_verifikasi");

                    b.Property<int>("SyaratId")
                        .HasColumnType("integer")
                        .HasColumnName("syarat_id");

                    b.Property<DateTime>("TanggalUnggah")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_unggah");

                    b.HasKey("DokumenId");

                    b.HasIndex("PengajuanId");

                    b.HasIndex("SyaratId");

                    b.ToTable("portal_dokumen_penerima");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalHelpdeskTiket", b =>
                {
                    b.Property<int>("TiketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tiket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TiketId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DijawabOlehUserId")
                        .HasColumnType("integer")
                        .HasColumnName("dijawab_oleh_user_id");

                    b.Property<string>("JawabanAdmin")
                        .HasColumnType("text")
                        .HasColumnName("jawaban_admin");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategori");

                    b.Property<string>("NomorTiket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomor_tiket");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pesan");

                    b.Property<int>("StatusTiket")
                        .HasColumnType("integer")
                        .HasColumnName("status_tiket");

                    b.Property<string>("Subjek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjek");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TiketId");

                    b.HasIndex("DijawabOlehUserId");

                    b.HasIndex("UserId");

                    b.ToTable("portal_helpdesk_tiket");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalPengumuman", b =>
                {
                    b.Property<int>("PengumumanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pengumuman_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PengumumanId"));

                    b.Property<string>("GambarCoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("gambar_cover_url");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("IsiKonten")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isi_konten");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("judul");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategori");

                    b.Property<int?>("PenulisUserId")
                        .HasColumnType("integer")
                        .HasColumnName("penulis_user_id");

                    b.Property<string>("Ringkasan")
                        .HasColumnType("text")
                        .HasColumnName("ringkasan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime>("TanggalTerbit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_terbit");

                    b.HasKey("PengumumanId");

                    b.HasIndex("PenulisUserId");

                    b.ToTable("portal_pengumuman");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalSyaratDokumen", b =>
                {
                    b.Property<int>("SyaratId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("syarat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SyaratId"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<string>("FormatFileDiizinkan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format_file_diizinkan");

                    b.Property<int>("MaxSizeMb")
                        .HasColumnType("integer")
                        .HasColumnName("max_size_mb");

                    b.Property<string>("NamaDokumen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_dokumen");

                    b.Property<string>("TipePenerima")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipe_penerima");

                    b.Property<bool>("Wajib")
                        .HasColumnType("boolean")
                        .HasColumnName("wajib");

                    b.HasKey("SyaratId");

                    b.ToTable("portal_syarat_dokumen");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AlumniKontribusi", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany("DaftarKontribusi")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AlumniTracerKarir", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany("RiwayatKarir")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppPengurus", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "User")
                        .WithOne("PengurusProfile")
                        .HasForeignKey("AlIkhwanBeasiswa.Core.Entities.AppPengurus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppRolePermission", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUserProfile", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany()
                        .HasForeignKey("MahasiswaId");

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", "Siswa")
                        .WithMany()
                        .HasForeignKey("SiswaId");

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "User")
                        .WithOne("RecipientProfile")
                        .HasForeignKey("AlIkhwanBeasiswa.Core.Entities.AppUserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");

                    b.Navigation("Siswa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUserRole", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.ApprovalBeasiswa", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", "Pengajuan")
                        .WithMany("DaftarApproval")
                        .HasForeignKey("PengajuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("Pengajuan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanOrangTua", "OrangTua")
                        .WithMany("AnakMahasiswa")
                        .HasForeignKey("OrangTuaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrangTua");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanNilaiSekolah", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanPendidikan", "Pendidikan")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("PendidikanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", "Siswa")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pendidikan");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanNilaiUniv", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanUniversitas", "Universitas")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("UniversitasUnivId");

                    b.Navigation("Mahasiswa");

                    b.Navigation("Universitas");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanPendidikan", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", "Siswa")
                        .WithMany("RiwayatPendidikan")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanOrangTua", "OrangTua")
                        .WithMany("AnakSiswa")
                        .HasForeignKey("OrangTuaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrangTua");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanUniversitas", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany("RiwayatUniversitas")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiPresensi", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.KaderisasiKegiatan", "Kegiatan")
                        .WithMany("DaftarPresensi")
                        .HasForeignKey("KegiatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany()
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kegiatan");

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiProfil", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithOne("KaderisasiProfile")
                        .HasForeignKey("AlIkhwanBeasiswa.Core.Entities.KaderisasiProfil", "MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PencairanBeasiswa", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "DicairkanOlehUser")
                        .WithMany()
                        .HasForeignKey("DicairkanOlehUserId");

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", "Pengajuan")
                        .WithMany("DaftarPencairan")
                        .HasForeignKey("PengajuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DicairkanOlehUser");

                    b.Navigation("Pengajuan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", "Mahasiswa")
                        .WithMany("DaftarPengajuanBeasiswa")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.PeriodeBeasiswa", "Periode")
                        .WithMany("DaftarPengajuan")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", "Siswa")
                        .WithMany("DaftarPengajuanBeasiswa")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mahasiswa");

                    b.Navigation("Periode");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalDokumenPenerima", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", "Pengajuan")
                        .WithMany("BerkasDokumen")
                        .HasForeignKey("PengajuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.PortalSyaratDokumen", "Syarat")
                        .WithMany("DokumenTerunggah")
                        .HasForeignKey("SyaratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengajuan");

                    b.Navigation("Syarat");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalHelpdeskTiket", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "DijawabOlehUser")
                        .WithMany()
                        .HasForeignKey("DijawabOlehUserId");

                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DijawabOlehUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalPengumuman", b =>
                {
                    b.HasOne("AlIkhwanBeasiswa.Core.Entities.AppUser", "PenulisUser")
                        .WithMany()
                        .HasForeignKey("PenulisUserId");

                    b.Navigation("PenulisUser");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.AppUser", b =>
                {
                    b.Navigation("PengurusProfile");

                    b.Navigation("RecipientProfile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanMahasiswa", b =>
                {
                    b.Navigation("DaftarKontribusi");

                    b.Navigation("DaftarNilai");

                    b.Navigation("DaftarPengajuanBeasiswa");

                    b.Navigation("KaderisasiProfile");

                    b.Navigation("RiwayatKarir");

                    b.Navigation("RiwayatUniversitas");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanOrangTua", b =>
                {
                    b.Navigation("AnakMahasiswa");

                    b.Navigation("AnakSiswa");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanPendidikan", b =>
                {
                    b.Navigation("DaftarNilai");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanSiswa", b =>
                {
                    b.Navigation("DaftarNilai");

                    b.Navigation("DaftarPengajuanBeasiswa");

                    b.Navigation("RiwayatPendidikan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.IkhwanUniversitas", b =>
                {
                    b.Navigation("DaftarNilai");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.KaderisasiKegiatan", b =>
                {
                    b.Navigation("DaftarPresensi");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PengajuanBeasiswa", b =>
                {
                    b.Navigation("BerkasDokumen");

                    b.Navigation("DaftarApproval");

                    b.Navigation("DaftarPencairan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PeriodeBeasiswa", b =>
                {
                    b.Navigation("DaftarPengajuan");
                });

            modelBuilder.Entity("AlIkhwanBeasiswa.Core.Entities.PortalSyaratDokumen", b =>
                {
                    b.Navigation("DokumenTerunggah");
                });
#pragma warning restore 612, 618
        }
    }
}
